; OPcache
opcache.enable=1
opcache.enable_cli=1
opcache.memory_consumption=512
opcache.interned_strings_buffer=32
opcache.max_accelerated_files=40000
opcache.validate_timestamps=0
opcache.save_comments=0
opcache.fast_shutdown=1
opcache.huge_code_pages=1

; Cache persistente no disco
opcache.file_cache=/tmp/.opcache
opcache.file_cache_only=0
opcache.file_cache_consistency_checks=0
opcache.file_cache_fallback=1

; JIT otimizado para Alder Lake (P+E cores)
opcache.jit_buffer_size=512M
opcache.jit=tracing
opcache.jit_max_root_traces=0
opcache.jit_max_side_traces=0
opcache.jit_hot_func=127
opcache.jit_hot_loop=64
opcache.jit_hot_return=8
opcache.jit_hot_side_exit=8